/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnexosRouteImport } from './routes/anexos'
import { Route as BitacoraRouteImport } from './routes/bitacora'
import { Route as DescargarRouteImport } from './routes/descargar'
import { Route as DocumentoRouteImport } from './routes/documento'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as ApiGeminiRouteImport } from './routes/api/gemini'
import { Route as ApiInvestigateRouteImport } from './routes/api/investigate'
import { Route as ApiValidateUrlRouteImport } from './routes/api/validate-url'
import { Route as ApiWordRouteImport } from './routes/api/word'
import { Route as SeccionIdRouteImport } from './routes/seccion.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnexosRoute = AnexosRouteImport.update({
  id: '/anexos',
  path: '/anexos',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraRoute = BitacoraRouteImport.update({
  id: '/bitacora',
  path: '/bitacora',
  getParentRoute: () => rootRouteImport,
} as any)
const DescargarRoute = DescargarRouteImport.update({
  id: '/descargar',
  path: '/descargar',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentoRoute = DocumentoRouteImport.update({
  id: '/documento',
  path: '/documento',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeminiRoute = ApiGeminiRouteImport.update({
  id: '/api/gemini',
  path: '/api/gemini',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvestigateRoute = ApiInvestigateRouteImport.update({
  id: '/api/investigate',
  path: '/api/investigate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValidateUrlRoute = ApiValidateUrlRouteImport.update({
  id: '/api/validate-url',
  path: '/api/validate-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWordRoute = ApiWordRouteImport.update({
  id: '/api/word',
  path: '/api/word',
  getParentRoute: () => rootRouteImport,
} as any)
const SeccionIdRoute = SeccionIdRouteImport.update({
  id: '/seccion/$id',
  path: '/seccion/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anexos': typeof AnexosRoute
  '/bitacora': typeof BitacoraRoute
  '/descargar': typeof DescargarRoute
  '/documento': typeof DocumentoRoute
  '/equipo': typeof EquipoRoute
  '/api/gemini': typeof ApiGeminiRoute
  '/api/investigate': typeof ApiInvestigateRoute
  '/api/validate-url': typeof ApiValidateUrlRoute
  '/api/word': typeof ApiWordRoute
  '/seccion/$id': typeof SeccionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anexos': typeof AnexosRoute
  '/bitacora': typeof BitacoraRoute
  '/descargar': typeof DescargarRoute
  '/documento': typeof DocumentoRoute
  '/equipo': typeof EquipoRoute
  '/api/gemini': typeof ApiGeminiRoute
  '/api/investigate': typeof ApiInvestigateRoute
  '/api/validate-url': typeof ApiValidateUrlRoute
  '/api/word': typeof ApiWordRoute
  '/seccion/$id': typeof SeccionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anexos': typeof AnexosRoute
  '/bitacora': typeof BitacoraRoute
  '/descargar': typeof DescargarRoute
  '/documento': typeof DocumentoRoute
  '/equipo': typeof EquipoRoute
  '/api/gemini': typeof ApiGeminiRoute
  '/api/investigate': typeof ApiInvestigateRoute
  '/api/validate-url': typeof ApiValidateUrlRoute
  '/api/word': typeof ApiWordRoute
  '/seccion/$id': typeof SeccionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anexos'
    | '/bitacora'
    | '/descargar'
    | '/documento'
    | '/equipo'
    | '/api/gemini'
    | '/api/investigate'
    | '/api/validate-url'
    | '/api/word'
    | '/seccion/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anexos'
    | '/bitacora'
    | '/descargar'
    | '/documento'
    | '/equipo'
    | '/api/gemini'
    | '/api/investigate'
    | '/api/validate-url'
    | '/api/word'
    | '/seccion/$id'
  id:
    | '__root__'
    | '/'
    | '/anexos'
    | '/bitacora'
    | '/descargar'
    | '/documento'
    | '/equipo'
    | '/api/gemini'
    | '/api/investigate'
    | '/api/validate-url'
    | '/api/word'
    | '/seccion/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnexosRoute: typeof AnexosRoute
  BitacoraRoute: typeof BitacoraRoute
  DescargarRoute: typeof DescargarRoute
  DocumentoRoute: typeof DocumentoRoute
  EquipoRoute: typeof EquipoRoute
  ApiGeminiRoute: typeof ApiGeminiRoute
  ApiInvestigateRoute: typeof ApiInvestigateRoute
  ApiValidateUrlRoute: typeof ApiValidateUrlRoute
  ApiWordRoute: typeof ApiWordRoute
  SeccionIdRoute: typeof SeccionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anexos': {
      id: '/anexos'
      path: '/anexos'
      fullPath: '/anexos'
      preLoaderRoute: typeof AnexosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora': {
      id: '/bitacora'
      path: '/bitacora'
      fullPath: '/bitacora'
      preLoaderRoute: typeof BitacoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descargar': {
      id: '/descargar'
      path: '/descargar'
      fullPath: '/descargar'
      preLoaderRoute: typeof DescargarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documento': {
      id: '/documento'
      path: '/documento'
      fullPath: '/documento'
      preLoaderRoute: typeof DocumentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gemini': {
      id: '/api/gemini'
      path: '/api/gemini'
      fullPath: '/api/gemini'
      preLoaderRoute: typeof ApiGeminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/investigate': {
      id: '/api/investigate'
      path: '/api/investigate'
      fullPath: '/api/investigate'
      preLoaderRoute: typeof ApiInvestigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/validate-url': {
      id: '/api/validate-url'
      path: '/api/validate-url'
      fullPath: '/api/validate-url'
      preLoaderRoute: typeof ApiValidateUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/word': {
      id: '/api/word'
      path: '/api/word'
      fullPath: '/api/word'
      preLoaderRoute: typeof ApiWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seccion/$id': {
      id: '/seccion/$id'
      path: '/seccion/$id'
      fullPath: '/seccion/$id'
      preLoaderRoute: typeof SeccionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnexosRoute: AnexosRoute,
  BitacoraRoute: BitacoraRoute,
  DescargarRoute: DescargarRoute,
  DocumentoRoute: DocumentoRoute,
  EquipoRoute: EquipoRoute,
  ApiGeminiRoute: ApiGeminiRoute,
  ApiInvestigateRoute: ApiInvestigateRoute,
  ApiValidateUrlRoute: ApiValidateUrlRoute,
  ApiWordRoute: ApiWordRoute,
  SeccionIdRoute: SeccionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
